### ISSUE TITLE
Why is ontology rejected?

### ISSUE THREAD

**Issue by pacass** [dbpedia/archivo#11]
I tried to suggest another ontology for Archivo and it was rejected.  It loads just fine in OWL version 5 or 3.5.
  Check this and figure out the problem, and let me know what to do.
       http://micra.com/COSMO/COSMO.owl 

Pat Cassidy
cassidy@micra.com

**Comment by yum-yab** [comment]
Hi,
i looked at the problem and the problem was on archivos side, the tests took too long and the process timed out.

I've fixed the problem and here is the report page of the ontology: https://archivo.dbpedia.org/info?o=http://micra.com/COSMO/COSMO.owl

If you want to fix the problems of your ontology, check out https://archivo.dbpedia.org/rating for help.

Regards,
Denis

**Comment by pacass** [comment]
Thanks a lot.  

The verification may have taken a lot of time because of the size and complexity of the ontology.  With over 24,00 classes and 1300 ObjectProperties and

20,000 restrictions, the consistency check on OWL takes over 1 hour.  The size is the point of the ontology.  I am trying to represent the most common words of English to support broad general interoperability.   More to go.

 

Congratulations on maintaining the site.  I hope it can continue to be supported.

 

Pat

 

Patrick Cassidy

MICRA Inc.

cassidy@micra.com

1-908-561-3416

**Comment by pacass** [comment]
Thanks for the info on star ratings.

The ontology is consistent using both Pellet and Fact++, but Pellet can use up to 13 GB of memory and may bomb with this ontology if insufficient memory is available, and it takes over an hour and a half on an i7 chip.  As it gets bigger, this nuisance will get worse.

 

The ontology is freely usable, but availability is not completely public domain only because parts (comments) of the ontology are taken from the OpenCYC ontology, which is freely usable but requires attribution.   Other comments are taken from WordNet, and SUMO, also requiring attribution.  This is discussed in comment text at the top of the text file.  Not sure exactly how to satisfy Archivo’s need for such info.  Pointer?

 

Pat

 

Patrick Cassidy

MICRA Inc.

cassidy@micra.com

1-908-561-3416
