### ISSUE TITLE
There is a problem with proxying to the DBpedia Archivo frontend. 

### ISSUE THREAD

**Issue by tiwari2019** [dbpedia/archivo#19]
There is a problem with proxying to the DBpedia Archivo frontend.

**Comment by yum-yab** [comment]
Hi, in what case did this happen? Was Archivo simply unavailable or did you something?

**Comment by k00ni** [comment]
Happened to me as well (around 4:36 pm).

![Bildschirmfoto vom 2024-02-28 16-33-25](https://github.com/dbpedia/archivo/assets/381727/20f78073-71ef-4ee3-a53a-cf63af18eae1)

I was just working on a simple script which queries https://archivo.dbpedia.org/list from time to time, maybe once every 5 minutes. It shouldn't impact the server load that much. Reloading the page brings no relief.

**Comment by k00ni** [comment]
It is back online (around 4:40 pm).

**Comment by JJ-Author** [comment]
sorry the vpn on the server messed up with the network connection that is why it was temporarily not available from some areas.

**Comment by JJ-Author** [comment]
in general this is a proxy fallback page intended to be shown if the archivo-backend/gateway is unresponsive or is not reachable.
in case of tiwari19`s case it was triggered by the connection timeout of that proxy likely when adding an ontology to archivo.
I increased the timeout now to 39600 seconds (11 hours) such that should not occur no more.
