### ISSUE TITLE
updated snapshots

### ISSUE THREAD

**Issue by stap-m** [dbpedia/archivo#32]
Hello archivo developers, 
Is there kind of a schedule when new snapshots are taken? Currently, you don't refer to the latest released version of [OEO](https://archivo.dbpedia.org/info?o=http://openenergy-platform.org/ontology/oeo/), for example. 
Is there a way to inform you about new releases to take a further snapshot? Thanks!

**Comment by JJ-Author** [comment]
The schedule is 3 times a day. At the moment the OEO is not available to machines. I assume sth. was changed or got broken on the hosting side of OEO which is affecting Linked Data content negotiation to work properly and therefore Archivo will not be able to fetch a newer version of the OEO.

**Comment by stap-m** [comment]
Ok. thanks for the hint. We'll check that.

**Comment by JJ-Author** [comment]
the new release has been fetched. pls reopen if there still is an issue.
